# Generated by Django 2.1 on 2018-10-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(default=None, upload_to='captures/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('first_login', models.BooleanField(default=True)),
                ('profile_pic', models.ImageField(default=None, null=True, upload_to='captures/')),
            ],
        ),
    ]
