# Generated by Django 2.1 on 2018-10-11 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_imagemodel_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='email',
        ),
    ]
